### ISSUE TITLE
Doesn't play nice with hidpi screens

### ISSUE THREAD

**Issue by lllama** [nccgroup/pip3line#5]
![image](https://user-images.githubusercontent.com/598411/31275218-44c70284-aa8e-11e7-9a87-c610cd15fc10.png)

**Comment by metrodango** [comment]
Which system/configuration are you using ?

**Comment by lllama** [comment]
Windows 10. Version 3.1.1 Compiled with Qt 5.7.0 (currently running with Qt 5.7.0).

4k screen on a Dell 5510

**Comment by metrodango** [comment]
Can you try with the RC version I send you, and confirm that this is fixed ?

**Comment by metrodango** [comment]
I do not have a fancy laptop to test it with ....

**Comment by metrodango** [comment]
v3.2.0 should fix this, closing for now

**Comment by lllama** [comment]
Can confirm that this is fixed in 3.3.0, though I had to change the font size. Can be set to whatever, it just needed to be changed at least once to trigger a redraw.
